image: golang:latest

only:
  - merge_request_closures
except:
  - /^(?!main|dev$).*$/

variables:
  - $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
  - TARGET_GO_REPOSITORY: $TARGET_GO_REPOSITORY
  - ACCESS_TOKEN: $ACCESS_TOKEN

stages:
  - lint
  # - breaking-change-checker
  - build
  - push

before_script:
  - image: bufbuild/buf:1.11.0
    entrypoint: [""] # force an empty entrypoint

lint:
  stage: lint
  script:
    - buf check lint

# breaking-change:
#   stage: breaking-change-checker
#   script:
#     - buf check lint

build:
  stage: build
  dependencies:
    - lint
    - breaking-change
  script:
    - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
    - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
    - export PATH="$PATH:$(go env GOPATH)/bin"
    - buf generate
    - ./
  artifacts:
    paths:
      - gen/
  when:
    - merge_request: merged
    - branch: dev
    - branch: main

push:
  stage: push
  dependencies:
    - build
  script:
    - ./scripts/push-proto/go-push.sh
  when:
    - merge_request: merged
    - branch: dev
    - branch: main
