name: Create Beta-Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm i semver@7.3.8
      - name: Create Beta Release
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.API_TOKEN_GITHUB }}"
          script: |
            const semver = require("semver");

            try{
                const response = await github.rest.repos.listTags({
                    owner : context.repo.owner,
                    repo: context.repo.repo,
                });
                const tags = response.data.map(tag => tag.name.toLowerCase());
            
                console.log("\n================== Beta-Release ==================");
                console.log("Tags: \n" , tags , "\n");
            
                let lastVersion;
                if (tags.length === 0) lastVersion = "v0.0.0";
                else lastVersion = tags[0];

                let newVersion = semver.inc(lastVersion , "patch");
                newVersion = `v${newVersion}`;
            
                if (!newVersion || !semver.valid(newVersion)) {
                  throw new Error(`Invalid New Version: ${newVersion}`);
                }

                console.log("New Beta-Version: " , newVersion , "\n");

                await github.rest.repos.createRelease({
                  tag_name: newVersion,
                  release_name: newVersion,
                  generate_release_notes: true,
                  draft: false,
                  prerelease: false,
                  make_latest: "false",
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });
                
                console.log("New Beta-Release Created: " , newVersion , "\n");
                console.log("===================================================\n");
            }
            catch (error) {
                core.setFailed(error.message);
            }
