name: Generate, Checking breaking change and Lint buf

on: push

env:
  GO_REPOSITORY: "protobuf-template-go"
  RELEASE_TAG: "test"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Buf Init
        uses: bufbuild/buf-setup-action@v1.9.0
        with:
          version: latest
      - name: Install protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
      - name: Buf Generate
        run: |
          export PATH="$PATH:$(go env GOPATH)/bin"
          buf generate
      - name: Init Go Module
        run: |
          cd gen/go
          go mod init github.com/infranyx/${{env.GO_REPOSITORY}}
          go mod tidy
          cd ../..
      - name: Pushes Generated Go Module
        uses: cpina/github-action-push-to-another-repository@v1.5.1
        env:
          # SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "gen/go"
          destination-github-username: "infranyx"
          destination-repository-name: ${{env.GO_REPOSITORY}}
          # user-email:
          target-branch: main
      - name: Create Golang Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Generated Golang Code
          draft: false
          prerelease: false
          owner: context.repo.owner
          repo: "github.com/infranyx/${{env.GO_REPOSITORY}}"
