name: Generate, Lint and Check Breaking Changes

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Buf Init
      uses: bufbuild/buf-setup-action@v1.9.0
      with:
        version: latest
    - name: Install protoc-gen-go
      run: |
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
    - name: Buf Generate
      run: |
        export PATH="$PATH:$(go env GOPATH)/bin"
        buf generate
    - name: Buf Lint
      run: |
        buf lint
      
